"$schema" = 'https://starship.rs/config-schema.json'

right_format = """$aws$gcloud$direnv"""

[aws]
disabled=false
format = '[$symbol $profile]($style)'
style = 'dimmed yellow'
symbol="\ue7ad"
[aws.region_aliases]
us-east-1 = 'us'
ca-central-1 = 'ca'
[aws.profile_aliases]
default-long-term = ' '
telus-lagoon = '󰰦 '
personal = ' '

[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"
vimcmd_symbol = "[](bold cyan)"

[cmd_duration]
min_time=1000
format = "[ $duration](bold yellow)"

[conda]
format= '\[[$symbol($environment)]($style)\]'

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 1
read_only = " "

[direnv]
format= '[$symbol]($style)'
symbol = " "
disabled = false
style = "bold black"

[gcloud]
disabled=false
symbol=" 󱇶 "
format= '[$symbol]($style)'
detect_env_vars = [ 'GCLOUD_PROJECT' ]

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_statusahead_behind\]]($style))'

[lua]
symbol = ''
format = '\[[$symbol($version)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[elixir]
disabled=true

[golang]
symbol = '󰟓 '
format = '\[[$symbol($version)]($style)\]'
